version: '3.8'

services:
  snort:
    build:
      context: .
      dockerfile: Dockerfile
    image: dos_test/snort3:latest
    container_name: snort_ids
    privileged: true
    network_mode: "host"

    # --- Critical for Snort: Network & Privileges ---
    cap_add:
      - NET_ADMIN        # For network interface configuration
      - NET_RAW          # For raw packet access
      - SYS_NICE         # To allow Snort to raise its priority
      - IPC_LOCK         # Added for potential mmap requirements

    # --- Volumes for Configuration, Rules, and Logs ---
    # Mount local directories into the container
    volumes:
      - ./snort_config/snort.lua:/usr/local/etc/snort/snort.lua:ro
      - ./snort_config/snort_defaults.lua:/usr/local/etc/snort/snort_defaults.lua:ro
      - ./snort_config/file_magic.lua:/usr/local/etc/snort/file_magic.lua:ro
      - ./rules:/usr/local/etc/snort/rules:ro # Mount your custom rules (read-only)
      - ./snort_logs:/var/log/snort            # Mount a directory for Snort logs (read-write)

    # --- Environment Variables ---
    # These can override or supplement settings in snort.lua or be used by wrapper scripts
    environment:
      # SNORT_INTERFACE: eth0 # Set the interface Snort should listen on. This is usually configured in snort.lua's daq section.
      # HOME_NET: "192.168.1.0/24" # Can be set here to override snort.lua if your entrypoint script uses it.
      # EXTERNAL_NET: "!$HOME_NET"
      # RULE_PATH: "/usr/local/etc/snort/rules"
      TZ: "Etc/UTC" # Set timezone

    # --- Command to Run Snort ---
    # This command will run Snort in IDS mode using the specified configuration.
    # Adjust the interface (-i) and configuration (-c) as needed.
    # The -A full option enables full alerts.
    # The -l /var/log/snort specifies the logging directory (already mounted).
    # The --pcap-filter can be used if you want to apply a BPF filter.
    # Ensure the interface (e.g., eth0) exists and is the one mirrored by the switch.
    # command: >
    #   snort -c /usr/local/etc/snort/snort.lua 
    #         -R /usr/local/etc/snort/snort.lua # Also treat snort.lua as the main rules file for IPS policy mode if needed, or just use -c for IDS
    #         -i eth0                   # <<<<< IMPORTANT: Replace eth0 with your actual sniffing interface on Host2
    #         -l /var/log/snort         # Log directory
    #         -A full                   # Alert mode (full alerts)
    #         -k none                   # Checksum mode (none, all, etc.)
    #         --rule-path /usr/local/etc/snort/rules # Explicitly set rule path
    #         # --pcap-filter "not host 127.0.0.1" # Example BPF filter
    #         # --create-pidfile          # Creates a PID file
    #         # -D                        # Run in daemon mode (background)
    # command: ["tail", "-f", "/dev/null"] # Keep container running for debugging
    command: ["snort", "-c", "/usr/local/etc/snort/snort.lua", "-i", "eth0", "-A", "alert_fast", "-s", "65535", "-k", "none", "-l", "/var/log/snort"]
    # restart: unless-stopped # Optional: restart policy

# Optional: Define named volumes if you prefer them over bind mounts for logs
# volumes:
#   snort_logs_volume:
