version: '3.8'

services:
  snort:
    build:
      context: .
      dockerfile: Dockerfile
      # Optionally pass build arguments if you need to override defaults in Dockerfile
      # args:
      #   SNORT_VERSION: 3.1.70.0
      #   DAQ_VERSION: 3.0.12
    image: dos_test/snort3 # You can tag the image
    container_name: snort_ids
    restart: unless-stopped

    # --- Critical for Snort: Network & Privileges ---
    network_mode: "host"  # Use host networking to allow Snort to see all host interfaces
    privileged: true      # Needed for Snort to put interfaces into promiscuous mode and access raw sockets
    cap_add:
      - NET_ADMIN        # For network interface configuration
      - NET_RAW          # For raw packet access
      - SYS_NICE         # To allow Snort to raise its priority

    # --- Volumes for Configuration, Rules, and Logs ---
    # Mount local directories into the container
    volumes:
      - ./snort_config:/usr/local/etc/snort:ro # Mount your snort.lua and other .lua configs (read-only)
      - ./rules:/usr/local/etc/snort/rules:ro  # Mount your custom rules (read-only)
      # - ./builtin_rules:/usr/local/etc/snort/builtin_rules:ro # If you have local builtin_rules
      # - ./preproc_rules:/usr/local/etc/snort/preproc_rules:ro # If you have local preproc_rules
      - ./snort_logs:/var/log/snort            # Mount a directory for Snort logs (read-write)
      # Optional: If you need to pass specific CA certificates or other files
      # - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

    # --- Environment Variables ---
    # These can override or supplement settings in snort.lua or be used by wrapper scripts
    environment:
      # SNORT_INTERFACE: eth0 # Set the interface Snort should listen on. This is usually configured in snort.lua's daq section.
      # HOME_NET: "192.168.1.0/24" # Can be set here to override snort.lua if your entrypoint script uses it.
      # EXTERNAL_NET: "!$HOME_NET"
      # RULE_PATH: "/usr/local/etc/snort/rules"
      TZ: "Etc/UTC" # Set timezone

    # --- Command to Run Snort ---
    # This command will run Snort in IDS mode using the specified configuration.
    # Adjust the interface (-i) and configuration (-c) as needed.
    # The -A full option enables full alerts.
    # The -l /var/log/snort specifies the logging directory (already mounted).
    # The --pcap-filter can be used if you want to apply a BPF filter.
    # Ensure the interface (e.g., eth0) exists and is the one mirrored by the switch.
    command: >
      snort -c /usr/local/etc/snort/snort.lua 
            -R /usr/local/etc/snort/snort.lua # Also treat snort.lua as the main rules file for IPS policy mode if needed, or just use -c for IDS
            -i eth0                   # <<<<< IMPORTANT: Replace eth0 with your actual sniffing interface on Host2
            -l /var/log/snort         # Log directory
            -A full                   # Alert mode (full alerts)
            -k none                   # Checksum mode (none, all, etc.)
            --rule-path /usr/local/etc/snort/rules # Explicitly set rule path
            # --pcap-filter "not host 127.0.0.1" # Example BPF filter
            # --create-pidfile          # Creates a PID file
            # -D                        # Run in daemon mode (background)

    # Healthcheck (optional, basic example)
    # healthcheck:
    #   test: ["CMD-SHELL", "pgrep snort || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

# Optional: Define named volumes if you prefer them over bind mounts for logs
# volumes:
#   snort_logs_volume:
