version: '3.8'
services:
  sniffer:
    build:
      context: .
      dockerfile: Dockerfile
    image: dos-test-snort
    container_name: dos_test_sniffer_container
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
      - IPC_LOCK

    volumes:
      - ./rules:/etc/snort/rules:ro
    #  - ./snort_logs:/var/log/snort:rw
    #  - ../pcaps:/mnt/pcaps:ro

    environment:
      TZ: "Etc/UTC"
    user: "1000:1000"
    command: ["/bin/sh", "-c", "snort -A full -c /etc/snort/etc/snort.conf -r /mnt/pcaps/attacks.pcap -l /var/log/snort ; cat /var/log/snort/alert"]